version: "3.8"

services:
    db_thitracnghiem:
        image: mysql:8.0
        container_name: db_thitracnghiem
        environment:
            MYSQL_DATABASE: tracnghiem
            MYSQL_ROOT_PASSWORD: thitracnghiem
        volumes:
            - db_thitracnghiem_data:/var/lib/mysql
            - ./tracnghiem.sql:/docker-entrypoint-initdb.d/tracnghiem.sql
        ports:
            - "3306:3306"

volumes:
    db_thitracnghiem_data:
